### ISSUE TITLE
Replace SAML logout confirmation screenshot for 4.2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs-gluu-server-prod#13]
Replace [this](https://www.gluu.org/docs/gluu-server/4.2/img/saml/saml_slo_confirm.png) screenshot with attached one. 
![LogoutGlobalLocal](https://user-images.githubusercontent.com/7156097/87328042-888c8500-c4fa-11ea-88f6-404bcf75fae3.PNG)

**Comment by shmorri** [comment]
Replaced
