### ISSUE TITLE
Docker Installation in Linux is not Working 

### ISSUE THREAD

**Issue by varma-shipsy** [GluuFederation/docs-gluu-server-prod#145]
After using the cmd 

./pygluu-compose-linux-amd64.pyz up

and filling up the details getting error as, can anyone help in solving this issue 

![image](https://github.com/GluuFederation/docs-gluu-server-prod/assets/92160261/67ffc5fe-3735-4ce4-ae4a-6e54a9706388)

**Comment by philipp1992** [comment]
same issue
