### ISSUE TITLE
"Extra Libs" -- new section for 4.2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs-gluu-server-prod#15]
It's under "Configuration" > "Organization configuration". 
Need to add doc. 
![42_extraLibs](https://user-images.githubusercontent.com/7156097/87388640-d214b880-c56a-11ea-9bc8-e51b650d4283.PNG)

**Comment by shmorri** [comment]
Added to the [Custom Authn page](https://github.com/GluuFederation/docs-gluu-server-prod/blob/4.2/docs/source/authn-guide/customauthn.md#adding-libraries) and the oxTrust screenshots.
