### ISSUE TITLE
Section about SVC_CR_ROTATE should be added to Docker installation guide

### ISSUE THREAD

**Issue by Pepelac** [GluuFederation/docs-gluu-server-prod#58]
As per https://support.gluu.org/cache-refresh/8715/cache-refresh-not-running/#at63112 a new section should be added to installation docs to describe Cache Refresh from LDAP in case of Gluu Server Docker installation

**Comment by iromli** [comment]
The docs has been added at 7941e7acde4582b11efa8d39ca7d89a70b1e6764. The live version will be available in approx. 15 minutes.
