### ISSUE TITLE
Gluu Server - AWS Aurora & ECS Compatibility Enquiry

### ISSUE THREAD

**Issue by Tamimi360** [GluuFederation/docs-gluu-server-prod#82]
Hello Team,

I want to enquire if Gluu Server is compatible with AWS RDS MySQL and we can have a full setup over AWS ECS as a cloud-native app.

https://aws.amazon.com/rds/aurora/
https://aws.amazon.com/ecs/

**Comment by moabu** [comment]
its tested with RDS(Aurora) as we support that. We do have people running with ecs but we do not support it yet. Our default and recommendation is K8s for orchestration. ECS requires you to do a lot of work which if fine with you is fine with us. If you an later share the configuration in a doc we would be happy to to showcase it.
